### ISSUE TITLE
No instant update: Components move to Uncategorized in the selector window when tags are changed

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#346] opened 2017-01-19 11:34 UTC
**Prepare**:

1. Open the Select Component window.
2. Make sure the component you are going to use is present under its group according to its tag(s).
3. Keep the window open.

**Repro**:

1. Edit the component's XML file.
2. Change the value of the pal:tags attribute.
3. Check the Select Component window.

**Expected**: The component moves from one category to another according to the new tag(s).
**Actual**: The component moves to "Uncategorized".

**Workaround**: Close the window and open it again. The component is listed under its correct category.

**Comment by kasravi** [comment] 2017-01-19 14:27
Categories are built as the page structure so they remain the same as long as window is there. If you change the tag to something that is already in there it moves to that category without a problem. The actual bug is when you change the tag to something new while window is open, which then it move to Uncategorized instead of its own category. This is by design and won't be fixed now.

**Closed** 2017-01-20 12:43 UTC
Labels: bug, severity:medium, wontfix

**Comment by wwwysocki** [comment] 2017-01-25 08:35
> If you change the tag to something that is already in there it moves to that category without a problem.

True. Verified on 20170124.2
